
GtowerAchivements = {}
GtowerAchivements.Achivements = {}


ACHIVEMENTS = {}

ACHIVEMENTS.WALKTOOLONG = 1
ACHIVEMENTS.JUMPINGJACK = 2
ACHIVEMENTS.DONTPROVOKEADMIN = 3
ACHIVEMENTS.GTOWERADDICTION = 4
ACHIVEMENTS.ADMINABUSE = 5
ACHIVEMENTS.LONGSEATGETALIFE = 6
ACHIVEMENTS.TETRISMANYPOINTS = 7
ACHIVEMENTS.TETRISMUCHTIME = 8
//9 - DO NOT USE 9, IT IS BUGGED FROM THE OLD ARCADE JUNKIE

ACHIVEMENTS.TETRIS4ONETIME = 10
ACHIVEMENTS.TETRIS1000AGAME = 11
ACHIVEMENTS.TICTACTOEWIN = 12
ACHIVEMENTS.TICTACTOEPERSITANT = 13

ACHIVEMENTS.SUITEOCD = 14
ACHIVEMENTS.SUITEPICKUPLINE = 15
ACHIVEMENTS.SUITELADYAFF = 16
ACHIVEMENTS.SUITEYOUTUBE = 17

ACHIVEMENTS.ZELDAFANBOY = 18
ACHIVEMENTS.FANCYPANTS = 19
ACHIVEMENTS.TRIVIAMASTER = 20
ACHIVEMENTS.drunkenbastard = 21
ACHIVEMENTS.HUMANBLUR = 22
ACHIVEMENTS.GARBAGEDAY = 23

ACHIVEMENTS.SUITEPOKERFACE = 24 //disabled
ACHIVEMENTS.CANDYCORNCONSUMER = 25

ACHIVEMENTS.ArcadeJunkie = 26

ACHIVEMENTS.DVNO = 27 //disabled

ACHIVEMENTS.SMARTINVESTER = 28
ACHIVEMENTS.HOLEINPOCKET = 29

ACHIVEMENTS.HUGMYLIFE = 30
ACHIVEMENTS.ZOMBIERP = 31
ACHIVEMENTS.CURIOUSCAT = 32
ACHIVEMENTS.TRASHCOMPACTOR = 33
ACHIVEMENTS.MILLIONAIRE = 34
ACHIVEMENTS.ONESMALLSTEP = 35

ACHIVEMENTS.PVPOVERKILL = 36
//ACHIVEMENTS.PVPABORTIONIST = 37
ACHIVEMENTS.PVPLAZOR = 38
ACHIVEMENTS.PVPDAMNEDDOG = 39
ACHIVEMENTS.PVPONTHEBRINK = 40
ACHIVEMENTS.PVPVETERAN = 41
ACHIVEMENTS.PVPHACKER = 42
ACHIVEMENTS.PVPTRUEHACKER = 43
ACHIVEMENTS.PVPTHEKID = 44
ACHIVEMENTS.PVPEAGLEEYE = 45

ACHIVEMENTS.BRUNPOPABLE = 46
ACHIVEMENTS.BRLASTINLINE = 47
ACHIVEMENTS.BRBALLERROLL = 48
ACHIVEMENTS.BRBANANABINGER = 49
ACHIVEMENTS.BRSPEEDSTER = 50

ACHIVEMENTS.MGREDBARON = 51
//ACHIVEMENTS.MGGIBBIG = 52
ACHIVEMENTS.MGCOLDKILLER = 53

ACHIVEMENTS.BRMASTER = 54

ACHIVEMENTS.PILLSHERE = 55

ACHIVEMENTS.SUITELEAVEMEALONE = 56
ACHIVEMENTS.SUITEPARTY = 57

ACHIVEMENTS.VIRUSTEAMPLAYER = 58
ACHIVEMENTS.VIRUSSTRONG = 59
ACHIVEMENTS.VIRUSDRUGGIE = 60
ACHIVEMENTS.VIRUSOVERDOSE = 61
ACHIVEMENTS.VIRUSPANDEMIC = 62
ACHIVEMENTS.VIRUSEXPLOSIVE = 63
ACHIVEMENTS.VIRUSLASTALIVE = 64
ACHIVEMENTS.VIRUSSHELLAWARE = 65
ACHIVEMENTS.VIRUSBRAGGING = 66
ACHIVEMENTS.VIRUSLOSTHOPE = 67
ACHIVEMENTS.VIRUSTIMESPLIT = 68


ACHIVEMENTS.BRMILESTONE1 = 69
ACHIVEMENTS.BRMILESTONE2 = 70
ACHIVEMENTS.PVPMILESTONE1 = 71
ACHIVEMENTS.PVPMILESTONE2 = 72
ACHIVEMENTS.VIRUSMILESTONE1 = 73
ACHIVEMENTS.VIRUSMILESTONE2 = 74 //use for later

ACHIVEMENTS.BRMEMORIES = 75

ACHIVEMENTS.UCHCAPE = 76
ACHIVEMENTS.UCHBUTTON = 77
ACHIVEMENTS.UCHDRUNKEN = 78
ACHIVEMENTS.UCHAERIAL = 79
ACHIVEMENTS.UCHTAUNTING = 80
ACHIVEMENTS.UCHDYNASTY = 81
ACHIVEMENTS.UCHBACON = 82
ACHIVEMENTS.UCHCHOMP = 83
ACHIVEMENTS.UCHENTERTHEPIG = 84
ACHIVEMENTS.UCHPANCAKE = 85
ACHIVEMENTS.UCHHOMERUN = 86

ACHIVEMENTS.BRTHATSARECORD = 87
ACHIVEMENTS.BRHARDERBETTERFASTERSTRONGER = 88

/*ACHIVEMENTS.BRSECRETGRASSWORLD = 89
ACHIVEMENTS.BRSECRETICEWORLD = 90
ACHIVEMENTS.BRSECRETKHROMIDRO = 91
ACHIVEMENTS.BRSECRETMEMORIES = 92
ACHIVEMENTS.BRSECRETMIDORI = 93
ACHIVEMENTS.BRSECRETPARADISE = 94
ACHIVEMENTS.BRSECRETSANDWORLD = 95
ACHIVEMENTS.BRSECRETSKYWORLD = 96
ACHIVEMENTS.BRSECRETFACILE = 97
ACHIVEMENTS.BRSECRETMETALWORLD = 98
ACHIVEMENTS.BRSECRETNIGHTWORLD = 99
ACHIVEMENTS.BRSECRETPRISM = 100
ACHIVEMENTS.BRSECRETSPACEWORLD = 101
ACHIVEMENTS.BRSECRETSUMMIT = 102
ACHIVEMENTS.BRSECRETTRANQUIL = 103
ACHIVEMENTS.BRSECRETWATERWORLD = 104
ACHIVEMENTS.BRSECRETFLYINHIGH = 105
ACHIVEMENTS.BRSECRETNEONLIGHTS = 106*/

ACHIVEMENTS.PLAYERMODEL = 107

/*ACHIVEMENTS.MONOHOARDER = 108
ACHIVEMENTS.MONOVANGOGH = 109
ACHIVEMENTS.MONOMODERNART = 110
ACHIVEMENTS.MONOARCHAEOLOGIST = 111
ACHIVEMENTS.MONOBALLOONHUNTER = 112*/

ACHIVEMENTS.PVPBIGBOSS = 113
ACHIVEMENTS.CELEBRATEGOODTIMES = 114

ACHIVEMENTS.MINIHOLEINONE = 122
ACHIVEMENTS.MINILONGDRIVE = 123
ACHIVEMENTS.MINILOFT = 124
ACHIVEMENTS.MINILONGPUTT = 125
ACHIVEMENTS.MINIMASTERS = 126
ACHIVEMENTS.MINIEAGLES = 127
ACHIVEMENTS.MINIALBATROSS = 128
ACHIVEMENTS.MINIBIRDIE = 129
ACHIVEMENTS.MINIGREENGREENS = 130
ACHIVEMENTS.MINIWATERHOLEPAR = 131
ACHIVEMENTS.MINISANDBARPAR = 132

--ACHIVEMENTS.BRSECRETMIRACLE = 133

ACHIVEMENTS.GRHAMMER = 134
ACHIVEMENTS.GRRACER = 135
ACHIVEMENTS.GROFFYOUGO = 136
ACHIVEMENTS.GRBOTTOM = 137
ACHIVEMENTS.GRUNTOUCHABLE = 138
ACHIVEMENTS.GRMILESTONE1 = 139

ACHIVEMENTS.SKPOWERUP = 140
ACHIVEMENTS.SKHITPOWERUP = 141
ACHIVEMENTS.SKDRIFT = 142
ACHIVEMENTS.SKDRIVE = 143
ACHIVEMENTS.SKSHOCK = 144
ACHIVEMENTS.SKCHAMP = 145
ACHIVEMENTS.SKLASER = 146
ACHIVEMENTS.SKROLLING = 147
ACHIVEMENTS.SKTELEPORT = 148
ACHIVEMENTS.SKOUTRUN = 149
ACHIVEMENTS.SKTURBO = 150

ACHIVEMENTS.ZMTESLA = 151
ACHIVEMENTS.ZMRADIO = 152
ACHIVEMENTS.ZMHEALKIT = 153
ACHIVEMENTS.ZMFOCUS = 154
ACHIVEMENTS.ZMBLADETRAP = 155
ACHIVEMENTS.ZMGHOSTBUSTER = 156
ACHIVEMENTS.ZMDOGKILL = 157
ACHIVEMENTS.ZMDAWNOFTHEDEAD = 158
ACHIVEMENTS.ZMSPIDER = 159
ACHIVEMENTS.ZM28DAYS = 160
ACHIVEMENTS.ZMDINO = 161
ACHIVEMENTS.ZMWEAPONS = 162
ACHIVEMENTS.ZMGRAVESAVE = 163
ACHIVEMENTS.ZMMASSACRE = 164
ACHIVEMENTS.ZMMUTANT = 165
ACHIVEMENTS.ZMCOMBO = 166
ACHIVEMENTS.ZMNESGUITAR = 167
ACHIVEMENTS.ZMMELEE = 168
ACHIVEMENTS.ZMCAMERA = 169


ACHIVEMENTS.VIRUSMILESTONERADAR = 170

ACHIVEMENTS.MINIMILESTONE1 = 171

ACHIVEMENTS.UCHMILESTONE1 = 172
ACHIVEMENTS.UCHMILESTONE2 = 173

ACHIVEMENTS.HALLOWEENRIDE = 174
ACHIVEMENTS.HALLOWEENGHOST = 175



hook.Add("Initialize", "LoadAchivments", function()
	hook.Call("LoadAchivements")

	//Now that all achivements are loaded, it no longer needs to exist!
	hook.GetTable().LoadAchivements = nil
end )

hook.Add("LoadAchivements","AchiSharedAwards", function ()

	GtowerAchivements:Add( ACHIVEMENTS.PLAYERMODEL, {
	Name = "My Own Man",
	Description = "Purchase a new player model.",
	Value = 1,
})

	GtowerAchivements:Add( ACHIVEMENTS.drunkenbastard, {
		Name = "Drunken Bastard",
		Description = "Be drunk for more than 10 minutes straight.",
		Value = 10*60,
		GiveItem = "trophy_drunkenbastard"
	})

	GtowerAchivements:Add( ACHIVEMENTS.HUGMYLIFE, {
		Name = "Hug My Life",
		Description = "Suicide gun yourself 200 times.",
		Value = 200
	})

	GtowerAchivements:Add( ACHIVEMENTS.CURIOUSCAT, {
		Name = "Curious Cat",
		Description = "Open 50 mysterious cat sacks.",
		Value = 50
	})

	GtowerAchivements:Add( ACHIVEMENTS.PILLSHERE, {
		Name = "Pills Here!",
		Description = "Eat 50 painkillers.",
		Value = 50
	})

	GtowerAchivements:Add( ACHIVEMENTS.GARBAGEDAY, {
		Name = "Garbage Day",
		Description = "Break an empty bottle.",
		Value = 1
	})

	GtowerAchivements:Add( ACHIVEMENTS.TRASHCOMPACTOR, {
		Name = "Trash Compactor",
		Description = "Break 100 empty bottles.",
		Value = 100
	})

	GtowerAchivements:Add( ACHIVEMENTS.ONESMALLSTEP, {
		Name = "One Small Step for Man",
		Description = "Find the moon theater.",
		Value = 1
	})

	/*GtowerAchivements:Add( ACHIVEMENTS.DVNO, {
		Name = "DVNO 2010",
		Description = "Hear a song about four capital letters printed in gold.",
		Value = 1
	})*/

end )

/*
	Data = {
		Name = "" //Name of the achivement
		Description = ""
		Group  = "" //Group of the achivmement, for organazing the score board, leave "nil" for Other
		Value = 1 //A value for what is the maximun value of the achivement
		GetValue = function( val ) return val / 10 end // This function will be called client side when you want to get the value to be shown in the scoreboard
		GetMaxValue = function() return 30 end //This function will be called client side when you want to get the max value to be shown in the scoreboard
		GiveItem = nil //MysqlID of a item to deposit in the bank when the achivement is earned
		NotGiveSlot = false //By default, a slot in the bank will be added when an achivement with an GiveItem is earned, set this true if no slots should be added (WARNING: If it is true and the bank is full, no item will be given )
		BitValue = //If set to true, the achivement will be bit values, the "AddAchivement" takes an extra argument, and Value is the lenght of the string
	}
*/

local Values = {
	math.pow( 2, 8 ),
	math.pow( 2, 16 ),
	math.pow( 2, 32 )
}

function GtowerAchivements:Add( id, Data )

	if !id then
		ErrorNoHalt("Attention: Attempting to add " .. tostring(Data.Name) .. " with achivement id '0'\n")
		return
	end

	if self.Achivements[ id ] != nil then
		ErrorNoHalt("Attention: Attempting to add " .. tostring(Data.Name) .. " with achivement id of '"..id.."', a key that already exists\n")
		return
	end

	if Data.BitValue == true && Data.Value > 31 then
		Msg("WARNING: Achivement ".. tostring(Data.Name) .. "(".. tostring(id) ..") BIT VALUE IS BIGGER THAN 31 bits!")
	end

	local function GetNetworkInfo()
		if Data.Value <= 0 then
			Msg("ACHIVEMENT: value below ZERO of: " .. Data.Name .. "("..id..").")
		elseif Data.Value == 1 then
			return { "Bool", 1 }
		elseif Data.Value < Values[1] then
			return { "Char", 1, Values[1]/2-1 }
		elseif Data.Value < Values[2] then
			return { "Short", 2, Values[2]/2-1 }
		elseif Data.Value < Values[3] then
			return { "Long", 4, Values[3]/2-1 }
		else
			Msg("ACHIVEMENT: Maximun value of: " .. Data.Name .. "("..id..") is too large.")
		end
	end

	Data._NWInfo = GetNetworkInfo()

	self.Achivements[ id ] = Data
end

function GtowerAchivements:Get( id )
	return self.Achivements[ id ]
end
