// These mods are defined statically in cl_init
// and thus not networked other than their IDs
BONEMOD_NORMAL = 0
BONEMOD_CUTE = 1
BONEMOD_FAT = 2
BONEMOD_SKINNY = 3
BONEMOD_DKMODE = 4
BONEMOD_SMALLHEAD = 5
BONEMOD_BIGHEAD = 6
BONEMOD_FLAT = 7
BONEMOD_ALIEN = 8
BONEMOD_ADDICT = 9
BONEMOD_BOUNCER = 10
BONEMOD_BIGFOOT = 11
BONEMOD_CARTOON = 12
BONEMOD_PINHEAD = 13
BONEMOD_LADY = 14
BONEMOD_HANDY = 15
BONEMOD_HEADLESS = 16
BONEMOD_BIGPANTS = 17
BONEMOD_STICK = 18