
GtowerAchievements = {}
GtowerAchievements.Achievements = {}
GtowerAchievements.DefaultGMC = 500


ACHIEVEMENTS = {}

ACHIEVEMENTS.WALKTOOLONG = 1
ACHIEVEMENTS.JUMPINGJACK = 2
//ACHIEVEMENTS.DONTPROVOKEADMIN = 3
ACHIEVEMENTS.GTOWERADDICTION = 4
ACHIEVEMENTS.ADMINABUSE = 5
ACHIEVEMENTS.LONGSEATGETALIFE = 6
ACHIEVEMENTS.TETRISMANYPOINTS = 7
ACHIEVEMENTS.TETRISMUCHTIME = 8
//9 - DO NOT USE 9, IT IS BUGGED FROM THE OLD ARCADE JUNKIE

ACHIEVEMENTS.TETRIS4ONETIME = 10
ACHIEVEMENTS.TETRIS1000AGAME = 11
ACHIEVEMENTS.TICTACTOEWIN = 12
ACHIEVEMENTS.TICTACTOEPERSITANT = 13

ACHIEVEMENTS.SUITEOCD = 14
ACHIEVEMENTS.SUITEPICKUPLINE = 15
ACHIEVEMENTS.SUITELADYAFF = 16
ACHIEVEMENTS.SUITEYOUTUBE = 17

ACHIEVEMENTS.ZELDAFANBOY = 18
ACHIEVEMENTS.FANCYPANTS = 19
ACHIEVEMENTS.TRIVIAMASTER = 20
ACHIEVEMENTS.DRUNKENBASTARD = 21
ACHIEVEMENTS.HUMANBLUR = 22
ACHIEVEMENTS.DOMESTICABUSE = 23

ACHIEVEMENTS.SUITEPOKERFACE = 24 //disabled
ACHIEVEMENTS.CANDYCORNCONSUMER = 25

ACHIEVEMENTS.ARCADEJUNKIE = 26

ACHIEVEMENTS.DVNO = 27 //disabled

ACHIEVEMENTS.SMARTINVESTER = 28
ACHIEVEMENTS.HOLEINPOCKET = 29

ACHIEVEMENTS.HUGMYLIFE = 30
ACHIEVEMENTS.ZOMBIERP = 31
ACHIEVEMENTS.CURIOUSCAT = 32
ACHIEVEMENTS.TRASHCOMPACTOR = 33
ACHIEVEMENTS.MILLIONAIRE = 34
ACHIEVEMENTS.ONESMALLSTEP = 35

ACHIEVEMENTS.PVPOVERKILL = 36
//ACHIEVEMENTS.PVPABORTIONIST = 37
ACHIEVEMENTS.PVPLAZOR = 38
ACHIEVEMENTS.PVPDAMNEDDOG = 39
ACHIEVEMENTS.PVPONTHEBRINK = 40
ACHIEVEMENTS.PVPVETERAN = 41
ACHIEVEMENTS.PVPHACKER = 42
ACHIEVEMENTS.PVPTRUEHACKER = 43
ACHIEVEMENTS.PVPTHEKID = 44
ACHIEVEMENTS.PVPEAGLEEYE = 45

ACHIEVEMENTS.BRUNPOPABLE = 46
ACHIEVEMENTS.BRLASTINLINE = 47
ACHIEVEMENTS.BRBALLERROLL = 48
ACHIEVEMENTS.BRBANANABINGER = 49
ACHIEVEMENTS.BRSPEEDSTER = 50

ACHIEVEMENTS.MGREDBARON = 51
ACHIEVEMENTS.MGGIBBIG = 52
ACHIEVEMENTS.MGCOLDKILLER = 53

ACHIEVEMENTS.BRMASTER = 54

ACHIEVEMENTS.PILLSHERE = 55

ACHIEVEMENTS.SUITELEAVEMEALONE = 56
ACHIEVEMENTS.SUITEPARTY = 57

ACHIEVEMENTS.VIRUSTEAMPLAYER = 58
ACHIEVEMENTS.VIRUSSTRONG = 59
ACHIEVEMENTS.VIRUSDRUGGIE = 60
ACHIEVEMENTS.VIRUSOVERDOSE = 61
ACHIEVEMENTS.VIRUSPANDEMIC = 62
ACHIEVEMENTS.VIRUSEXPLOSIVE = 63
ACHIEVEMENTS.VIRUSLASTALIVE = 64
ACHIEVEMENTS.VIRUSSHELLAWARE = 65
ACHIEVEMENTS.VIRUSBRAGGING = 66
ACHIEVEMENTS.VIRUSLOSTHOPE = 67
ACHIEVEMENTS.VIRUSTIMESPLIT = 68


ACHIEVEMENTS.BRMILESTONE1 = 69
ACHIEVEMENTS.BRMILESTONE2 = 70
ACHIEVEMENTS.PVPMILESTONE1 = 71
ACHIEVEMENTS.PVPMILESTONE2 = 72
ACHIEVEMENTS.VIRUSMILESTONE1 = 73
//ACHIEVEMENTS.VIRUSMILESTONE2 = 74 //use for later


ACHIEVEMENTS.BRMEMORIES = 75

ACHIEVEMENTS.UCHCAPE = 76
ACHIEVEMENTS.UCHBUTTON = 77
ACHIEVEMENTS.UCHDRUNKEN = 78
ACHIEVEMENTS.UCHAERIAL = 79
ACHIEVEMENTS.UCHTAUNTING = 80
ACHIEVEMENTS.UCHDYNASTY = 81
ACHIEVEMENTS.UCHBACON = 82
ACHIEVEMENTS.UCHCHOMP = 83
ACHIEVEMENTS.UCHENTERTHEPIG = 84
ACHIEVEMENTS.UCHPANCAKE = 85
ACHIEVEMENTS.UCHHOMERUN = 86

ACHIEVEMENTS.ZMTESLA = 87
ACHIEVEMENTS.ZMRADIO = 88
ACHIEVEMENTS.ZMHEALKIT = 89
ACHIEVEMENTS.ZMFOCUS = 90
ACHIEVEMENTS.ZMBLADETRAP = 91
ACHIEVEMENTS.ZMGHOSTBUSTER = 92
ACHIEVEMENTS.ZMDOGKILL = 93
ACHIEVEMENTS.ZMDAWNOFTHEDEAD = 94
ACHIEVEMENTS.ZMSPIDER = 95
ACHIEVEMENTS.ZM28DAYS = 96
ACHIEVEMENTS.ZMDINO = 97
ACHIEVEMENTS.ZMEXTREME = 98
ACHIEVEMENTS.ZMWEAPONS = 99
ACHIEVEMENTS.ZMGRAVESAVE = 100
ACHIEVEMENTS.ZMMASSACRE = 101
ACHIEVEMENTS.ZMCOMBO = 102
ACHIEVEMENTS.ZMMUTANT = 103
ACHIEVEMENTS.ZMNESGUITAR = 104
ACHIEVEMENTS.ZMMELEE = 105
ACHIEVEMENTS.ZMCAMERA = 106

ACHIEVEMENTS.PLAYERMODEL = 107
ACHIEVEMENTS.GEOMETRICALLY = 108

ACHIEVEMENTS.UCHMILESTONE1 = 109
ACHIEVEMENTS.UCHMILESTONE2 = 110
ACHIEVEMENTS.UCHMILESTONE3 = 111

ACHIEVEMENTS.MONOARCHAEOLOGIST = 112
ACHIEVEMENTS.MONOBLIND = 113
ACHIEVEMENTS.MONOVANGOGH = 114
ACHIEVEMENTS.MONOHOARDER = 115
ACHIEVEMENTS.MONOMODERNART = 116
ACHIEVEMENTS.MONOFINISHEDSWAN = 117

ACHIEVEMENTS.VIRUSMILESTONE2 = 118
ACHIEVEMENTS.VIRUSMILESTONE3 = 119
ACHIEVEMENTS.HALLOWEENCANDY = 120
ACHIEVEMENTS.HALLOWEENRIDE = 121

ACHIEVEMENTS.MINIHOLEINONE = 122
ACHIEVEMENTS.MINILONGDRIVE = 123
ACHIEVEMENTS.MINILOFT = 124
ACHIEVEMENTS.MINILONGPUTT = 125
ACHIEVEMENTS.MINIMASTERS = 126
ACHIEVEMENTS.MINIEAGLES = 127
ACHIEVEMENTS.MINIALBATROSS = 128
ACHIEVEMENTS.MINIBIRDIE = 129
ACHIEVEMENTS.MINIGREENGREENS = 130
ACHIEVEMENTS.MINIWATERHOLEPAR = 131
ACHIEVEMENTS.MINISANDBARPAR = 132

ACHIEVEMENTS.SOREFINGER = 133
ACHIEVEMENTS.BIGBUX = 134
ACHIEVEMENTS.COUNTINGCARDS = 135
ACHIEVEMENTS.FLUSH = 136
ACHIEVEMENTS.STANDINGTALL = 137
ACHIEVEMENTS.MONEYWASTER = 138
ACHIEVEMENTS.ROYALWINNINGS = 139

ACHIEVEMENTS.SKPOWERUP = 140
ACHIEVEMENTS.SKHITPOWERUP = 141
ACHIEVEMENTS.SKDRIFT = 142
ACHIEVEMENTS.SKDRIVE = 143
ACHIEVEMENTS.SKSHOCK = 144
ACHIEVEMENTS.SKCHAMP = 145
ACHIEVEMENTS.SKLASER = 146
ACHIEVEMENTS.SKDWI = 147
ACHIEVEMENTS.SKROLLING = 148
ACHIEVEMENTS.SKTELEPORT = 149
ACHIEVEMENTS.SKOUTRUN = 150
ACHIEVEMENTS.SKTURBO = 151

ACHIEVEMENTS.HALLOWEENGHOST = 152
ACHIEVEMENTS.HALLOWEENSURVIVOR = 153
ACHIEVEMENTS.MINIMILESTONE1 = 154

/*
	Data = {
		Name = "" //Name of the achivement
		Description = ""
		Group  = "" //Group of the achivmement, for organazing the score board, leave "nil" for Other
		Value = 1 //A value for what is the maximun value of the achivement
		GetValue = function( val ) return val / 10 end // This function will be called client side when you want to get the value to be shown in the scoreboard
		GetMaxValue = function() return 30 end //This function will be called client side when you want to get the max value to be shown in the scoreboard
		GiveItem = nil //MysqlID of a item to deposit in the bank when the achivement is earned
		NotGiveSlot = false //By default, a slot in the bank will be added when an achivement with an GiveItem is earned, set this true if no slots should be added (WARNING: If it is true and the bank is full, no item will be given )
		BitValue = //If set to true, the achivement will be bit values, the "AddAchievement" takes an extra argument, and Value is the lenght of the string
	}
*/

local Values = {
	math.pow( 2, 8 ),
	math.pow( 2, 16 ),
	math.pow( 2, 32 )
}

function GtowerAchievements:Add( id, Data )

	if !id then
		ErrorNoHalt("Attention: Attempting to add " .. tostring(Data.Name) .. " with achivement id '0'\n")
		return
	end

	if self.Achievements[ id ] != nil then
		ErrorNoHalt("Attention: Attempting to add " .. tostring(Data.Name) .. " with achivement id of '"..id.."', a key that already exists\n")
		return
	end

	if Data.BitValue == true && Data.Value > 31 then
		Msg("WARNING: Achievement ".. tostring(Data.Name) .. "(".. tostring(id) ..") BIT VALUE IS BIGGER THAN 31 bits!")
	end

	local function GetNetworkInfo()
		if Data.Value <= 0 then
			Msg("ACHIEVEMENT: value below ZERO of: " .. Data.Name .. "("..id..").")
		elseif Data.Value == 1 then
			return { "Bool", 1 }
		elseif Data.Value < Values[1] then
			return { "Char", 1, Values[1]/2-1 }
		elseif Data.Value < Values[2] then
			return { "Short", 2, Values[2]/2-1 }
		elseif Data.Value < Values[3] then
			return { "Long", 4, Values[3]/2-1 }
		else
			Msg("ACHIEVEMENT: Maximun value of: " .. Data.Name .. "("..id..") is too large.")
		end
	end

	Data.Id = id
	Data._NWInfo = GetNetworkInfo()

	self.Achievements[ id ] = Data
end

function GtowerAchievements:Get( id )
	return self.Achievements[ id ]
end
